In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
dataset = pd.read_csv("TrainDataset.csv")
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [28]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

***choose column which only countable data repidated or there was not null value***

In [29]:
en_data = dataset[["Gender","Married"]]
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

# ***One Hot Encoding***

In [30]:
# sklearn is learn data and convert categorical data into numerical data
from sklearn.preprocessing import OneHotEncoder

In [31]:
# convert simple data into onehotEncoder
ohe = OneHotEncoder()
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1228 stored elements and shape (614, 4)>

In [32]:
# store oneHotEncoding data into array formate
ar = ohe.fit_transform(en_data).toarray()
ar

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [33]:
# store oneHotEncoder data into data frame formate
pd.DataFrame(ar, columns=[
    "Gender_Female",
    "Gender_Male",
    "Married_No",
    "Married_Yes"
])

     Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]

# ***Remove one column for reduce no. of column***

In [35]:
# remove first data from oneHot
ohe2 = OneHotEncoder(drop="first")
arr = ohe2.fit_transform(en_data).toarray()
arr

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [38]:
pd.DataFrame(arr, columns=[
    "Gender_Male",
    "Married_Yes"
])

     Gender_Male  Married_Yes
0            1.0          0.0
1            1.0          1.0
2            1.0          1.0
3            1.0          1.0
4            1.0          0.0
..           ...          ...
609          0.0          0.0
610          1.0          1.0
611          1.0          1.0
612          1.0          1.0
613          0.0          0.0

[614 rows x 2 columns]